services:
  db:
    image: postgres:15-alpine
    container_name: bot_postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: summarize
      POSTGRES_DB: my_bot_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: